# Generated by Django 2.1.7 on 2019-05-24 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinica', models.CharField(blank=True, default='', max_length=50)),
                ('medic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medici',
            },
        ),
        migrations.CreateModel(
            name='Nefropatie',
            fields=[
                ('id_nefropatie', models.AutoField(primary_key=True, serialize=False)),
                ('data_ora', models.DateTimeField()),
                ('rata_filtrare_glomerulara', models.FloatField()),
                ('albuminuria', models.FloatField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare Nefropatie',
                'verbose_name_plural': 'Inregistrari Nefropatie',
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nastere', models.DateField(null=True)),
                ('anticorpi', models.BooleanField(default=False)),
                ('varsta_debut', models.IntegerField(null=True)),
                ('hemoglobina_glicozilata', models.FloatField(null=True)),
                ('inaltime', models.IntegerField(null=True)),
                ('greutate', models.FloatField(null=True)),
                ('HOMA2_Beta', models.FloatField(null=True)),
                ('HOMA2_IR', models.FloatField(null=True)),
                ('cluster', models.CharField(blank=True, default='', max_length=50)),
                ('medic', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Medic', to_field='medic_id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pacient',
                'verbose_name_plural': 'Pacienti',
            },
        ),
        migrations.CreateModel(
            name='Reprezentare_Glicemie',
            fields=[
                ('id_reprezentare', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('moment_al_zilei', models.CharField(blank=True, default='', max_length=50)),
                ('valoare_glicemie', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru reprezentarea glicemiei',
                'verbose_name_plural': 'Inregistrari pentru reprezentarea glicemiei',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roluri',
            },
        ),
        migrations.CreateModel(
            name='Variabilitate_Glicemie',
            fields=[
                ('id_variabilitate', models.AutoField(primary_key=True, serialize=False)),
                ('data_ora', models.DateTimeField(default=datetime.datetime.today)),
                ('valoare_glicemie', models.FloatField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru analiza glicemiei',
                'verbose_name_plural': 'Inregistrari pentru analiza glicemiei',
            },
        ),
    ]
