# Generated by Django 2.1.3 on 2019-02-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nefropatie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_ora', models.DateTimeField()),
                ('rata_filtrare_glomerulara', models.FloatField()),
                ('albuminuria', models.FloatField()),
            ],
            options={
                'verbose_name': 'Inregistrare Nefropatie',
                'verbose_name_plural': 'Inregistrari Nefropatie',
            },
        ),
        migrations.CreateModel(
            name='Reprezentare_Glicemie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valoare_inainte_mic_dejun', models.IntegerField()),
                ('valoare_dupa_mic_dejun', models.IntegerField()),
                ('valoare_mic_dejun_pranz', models.IntegerField()),
                ('valoare_inainte_pranz', models.IntegerField()),
                ('valoare_pranz', models.IntegerField()),
                ('valoare_dupa_pranz', models.IntegerField()),
                ('valoare_mic_dejun', models.IntegerField()),
                ('valoare_pranz_cina', models.IntegerField()),
                ('valoare_cina', models.IntegerField()),
                ('valoare_dupa_cina', models.IntegerField()),
                ('valoare_inainte_culcare', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inregistrare pentru reprezentarea glicemiei',
                'verbose_name_plural': 'Inregistrari pentru reprezentarea glicemiei',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nume_rol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roluri',
            },
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('nume_utilizator', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('parola', models.CharField(max_length=1000)),
                ('data_inregistrare', models.DateField()),
                ('ultima_inregistrare', models.DateTimeField()),
                ('data_nastere', models.DateField()),
                ('anticorpi', models.BooleanField(default=False)),
                ('varsta_debut', models.IntegerField()),
                ('hemoglobina_glicozilata', models.FloatField()),
                ('inaltime', models.IntegerField()),
                ('greutate', models.FloatField()),
                ('HOMA2_Beta', models.FloatField()),
                ('HOMA2_IR', models.FloatField()),
                ('cluster', models.CharField(max_length=50)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Rol')),
            ],
            options={
                'verbose_name': 'Utilizator',
                'verbose_name_plural': 'Utilizatori',
            },
        ),
        migrations.CreateModel(
            name='Variabilitate_Glicemie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_ora', models.DateTimeField()),
                ('valoare_glicemie', models.FloatField()),
                ('nume_utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Utilizator')),
            ],
            options={
                'verbose_name': 'Inregistrare pentru analiza glicemiei',
                'verbose_name_plural': 'Inregistrari pentru analiza glicemiei',
            },
        ),
        migrations.AddField(
            model_name='reprezentare_glicemie',
            name='nume_utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Utilizator'),
        ),
        migrations.AddField(
            model_name='nefropatie',
            name='nume_utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Utilizator'),
        ),
    ]
