# Generated by Django 2.1.7 on 2019-05-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice_SiMS',
            fields=[
                ('id_sims', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('sex', models.CharField(blank=True, default='', max_length=20)),
                ('diabet_in_familie', models.BooleanField(default=False)),
                ('inaltime', models.FloatField()),
                ('varsta', models.IntegerField(null=True)),
                ('talie', models.FloatField()),
                ('glicemia', models.FloatField()),
                ('trigliceride', models.FloatField()),
                ('tensiune_sistolica', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('siMS_scor', models.FloatField(null=True)),
                ('siMS_scor_risc', models.FloatField(null=True)),
                ('PsiMS_scor', models.FloatField(null=True)),
                ('siMS_scor_ref', models.FloatField(null=True)),
                ('siMS_scor_risc_ref', models.FloatField(null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru indicele siMS',
                'verbose_name_plural': 'Inregistrari pentru indicele siMS',
            },
        ),
        migrations.CreateModel(
            name='Risc_Diabet',
            fields=[
                ('id_risc_diabet', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('conditie_glicemie_pe_nemancate', models.BooleanField(default=False, null=True)),
                ('conditie_glicemie_la_doua_ore', models.BooleanField(default=False, null=True)),
                ('conditie_circumferinta_talie', models.BooleanField(default=False, null=True)),
                ('conditie_hipertensiune', models.BooleanField(default=False, null=True)),
                ('conditie_colesterol', models.BooleanField(default=False, null=True)),
                ('conditie_hiperlipidemie', models.BooleanField(default=False, null=True)),
                ('scor_cmds', models.IntegerField(null=True)),
                ('scor_cmds_modificat', models.IntegerField(null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru calculatorul de risc diabetic',
                'verbose_name_plural': 'Inregistrari pentru calculatorul de risc diabetic',
            },
        ),
        migrations.CreateModel(
            name='Risc_Hipoglicemie',
            fields=[
                ('id_hipoglicemie', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('urgente_hipoglicemie', models.CharField(blank=True, default='', max_length=20)),
                ('urgente', models.CharField(blank=True, default='', max_length=20)),
                ('insulina', models.BooleanField(default=False)),
                ('derivate_sulfoniluree', models.BooleanField(default=False)),
                ('irc_severa_terminala', models.BooleanField(default=False)),
                ('varsta_sub_77', models.BooleanField(default=False)),
                ('rezultat', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru calculatorul de risc hipoglicemie',
                'verbose_name_plural': 'Inregistrari pentru calculatorul de risc hipoglicemie',
            },
        ),
        migrations.RemoveField(
            model_name='nefropatie',
            name='data_ora',
        ),
        migrations.AddField(
            model_name='nefropatie',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nefropatie',
            name='rezultat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nefropatie',
            name='unitate_masura',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nefropatie',
            name='albuminuria',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nefropatie',
            name='rata_filtrare_glomerulara',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='variabilitate_glicemie',
            name='data_ora',
            field=models.DateTimeField(),
        ),
    ]
