# Generated by Django 2.1.7 on 2019-04-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizator',
            name='HOMA2_Beta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='HOMA2_IR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cluster',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='data_nastere',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='greutate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='hemoglobina_glicozilata',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='id_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Rol'),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='inaltime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='varsta_debut',
            field=models.IntegerField(null=True),
        ),
    ]
