# Generated by Django 2.1.7 on 2019-04-20 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_auto_20190405_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reprezentare_glicemie',
            old_name='valoare_cina',
            new_name='valoare_glicemie',
        ),
        migrations.RemoveField(
            model_name='nefropatie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_dupa_cina',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_dupa_mic_dejun',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_dupa_pranz',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_inainte_culcare',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_inainte_mic_dejun',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_inainte_pranz',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_mic_dejun',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_mic_dejun_pranz',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_pranz',
        ),
        migrations.RemoveField(
            model_name='reprezentare_glicemie',
            name='valoare_pranz_cina',
        ),
        migrations.RemoveField(
            model_name='variabilitate_glicemie',
            name='id',
        ),
        migrations.AddField(
            model_name='nefropatie',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reprezentare_glicemie',
            name='moment_al_zilei',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reprezentare_glicemie',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variabilitate_glicemie',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variabilitate_glicemie',
            name='data_ora',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
