# Generated by Django 2.1.7 on 2019-05-24 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190523_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefropatie',
            name='rezultat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nefropatie',
            name='unitate_masura',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nefropatie',
            name='albuminuria',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nefropatie',
            name='data_ora',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nefropatie',
            name='rata_filtrare_glomerulara',
            field=models.FloatField(null=True),
        ),
    ]
