# Generated by Django 2.1.7 on 2019-05-24 18:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_auto_20190524_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risc_Diabet',
            fields=[
                ('id_risc_diabet', models.AutoField(primary_key=True, serialize=False)),
                ('conditie_glicemie_pe_nemancate', models.BooleanField(default=False, null=True)),
                ('conditie_glicemie_la_doua_ore', models.BooleanField(default=False, null=True)),
                ('conditie_circumferinta_talie', models.BooleanField(default=False, null=True)),
                ('conditie_hipertensiune', models.BooleanField(default=False, null=True)),
                ('conditie_colesterol', models.BooleanField(default=False, null=True)),
                ('conditie_hiperlipidemie', models.BooleanField(default=False, null=True)),
                ('scor_cmds', models.IntegerField(null=True)),
                ('scor_cmds_modificats', models.IntegerField(null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru calculatorul de risc diabetic',
                'verbose_name_plural': 'Inregistrari pentru calculatorul de risc diabetic',
            },
        ),
    ]
