# Generated by Django 2.1.7 on 2019-05-24 18:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0005_risc_diabet_risc_hipoglicemie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risc_diabet',
            old_name='scor_cmds_modificats',
            new_name='scor_cmds_modificat',
        ),
    ]
