# Generated by Django 2.1.7 on 2019-05-24 20:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0006_auto_20190524_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='risc_diabet',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
