# Generated by Django 2.1.7 on 2019-05-24 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0007_auto_20190524_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice_SiMS',
            fields=[
                ('id_sims', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('sex', models.CharField(blank=True, default='', max_length=20)),
                ('diabet_in_familie', models.BooleanField(default=False)),
                ('inaltime', models.FloatField()),
                ('talie', models.FloatField()),
                ('glicemia', models.FloatField()),
                ('trigliceride', models.FloatField()),
                ('tensiune_sistolica', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('siMS_scor', models.FloatField(null=True)),
                ('siMS_scor_risc', models.FloatField(null=True)),
                ('PsiMS_scor', models.FloatField(null=True)),
                ('siMS_scor_ref', models.FloatField(null=True)),
                ('siMS_scor_risc_ref', models.FloatField(null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inregistrare pentru indicele siMS',
                'verbose_name_plural': 'Inregistrari pentru indicele siMS',
            },
        ),
    ]
