# Generated by Django 2.1.7 on 2019-05-24 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0008_indice_sims_risc_hipoglicemie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice_sims',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nefropatie',
            name='data_ora',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='risc_diabet',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='variabilitate_glicemie',
            name='data_ora',
            field=models.DateTimeField(),
        ),
    ]
