# Generated by Django 2.1.7 on 2019-05-24 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0009_auto_20190524_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nefropatie',
            old_name='data_ora',
            new_name='data',
        ),
    ]
