# Generated by Django 2.1.7 on 2019-05-24 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0010_auto_20190525_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice_sims',
            name='varsta',
            field=models.IntegerField(null=True),
        ),
    ]
